---
title: Resume
type: "resume"
date: '2018-07-23'
---

Please click <a href="https://drive.google.com/file/d/1Y6lWTdblz8fLAZDDmT_03iZ9lTibr0Po/view" target="_blank">here</a> for the most up-to-date version of my resume.

<script>
  window.location.replace("https://drive.google.com/file/d/1Y6lWTdblz8fLAZDDmT_03iZ9lTibr0Po/view");
</script

<!--
# Gurudev Ilangovan

[www.linkedin.com/in/gurudevilangovan/](https://www.linkedin.com/in/gurudevilangovan/)    
[www.github.com/ilangurudev](https://www.github.com/ilangurudev")    
[ilangurudev@gmail.com](mailto:ilangurudev@gmail.com)    
[917-517-5013](tel:9175175013)    
<a href="https://drive.google.com/open?id=1x3RTYv7wBau9pH0Ds3PcKfj0Zgj8SB5n" target="_blank">PDF version</a>


---

### Profile      
A passionate data scientist looking to gain industry exposure in machine learning and data science.

---

### Education
**Masters in Computer Science**   
Texas A&M University, College Station, TX  
*Sep 2017 - Current*  
CGPA: 3.8/4.0

**Masters in Industrial Engineering**  
Texas A&M University, College Station, TX  
*Sep 2015 - Aug - 2017*  
CGPA: 3.9/4.0

---

### Experience

**Research Scientist**  
Texas A&M University  
*Jan 2017 - Present*    
- Working as a graduate research assistant in the population informatics lab under Dr. Hye-Chung Kum    
- Planning, managing and coding in a variety of software engineering/data science projects in the areas, entity
deduplication and sequential data mining    
- Engineering the entire data pipeline from data collection, cleaning, data management to statistical analysis    
- Writing up the analyses as reports and technical papers for publications in journals/conferences

**Graduate Teaching Assistant**   
Texas A&M University    
*August 2016 – December 2016*   
- Worked as a teaching assistant for the graduate course Engineering Data Analysis (ISEN 613) offered by Dr. Satish Bukkapatnam   
- Responsibilities included evaluating student performance, mentoring, maintaining student databases and
administering the online portal for the course    
- Aided in the preparation of weekly quizzes and assignments and assisting in weekly classes and lesson plans   

**Assistant Systems Engineer**    
Tata Consultancy Services, India    
*December 2014 – July 2015*   
- Underwent ".NET" training in TCS Training camp, Trivandrum where I used C# to create a web portal for
Talent Acquisition teams to procure employee user data and process, manage and optimize the collected
resources to meet procurement requirements.   
- Briefly worked in a manual testing team for Citi Credit project

---

### Projects

**Sequential Analysis of Suicide Data**   
*Fall 2017 - Current*   
- Working in an international collaboration between Texas A&amp;M, Duke University, Swansea University (UK), Edinburgh
Napier University (Scotland) and US Dept of Veteran Affairs to identify treatment patterns in suicidal PTSD patients       
- Created an R package to deploy the sequential data mining algorithm called “ApproxMap” as part of Phase I      
- Phase II will involve analyzing a huge dataset of suicidal patient treatments to identify efficient treatment patterns
and flag ineffective ones   

**Privacy Preserving Interactive Record Linkage**      
*Spring 2017*      
- Worked in a research team to create a manual framework that facilitates accurate linkage of two databases without
compromising on privacy using principles of data masking and required disclosure      
- Co-authored a paper called “Balancing Privacy and Information Disclosure in Interactive Record Linkage with Visual
Masking” which has been nominated for Best Paper Award in the CHI Conference 2018, Montreal

**Evaluating Machine Learning Models for Record Linkage using Error Generation**       
*Spring 2018*      
- Creating an error generator package in R to artificially induce a wide range of record linkage based errors in a dataset
and a framework to effortlessly compare and study different algorithms’ effectiveness in different scenarios      
- Would be an easily extensible tool for selecting the best algorithm for performing linkage for the dataset at hand

**Identifying Manufacturing Process Shifts for Quality Control**       
*Fall 2016*      
- Identified the normal and assignable causes for variations in a manufacturing process and constructed multivariate
control charts using Hoteling T2 statistic and PCA, iteratively to monitor and identify the out-of-control parameters.

**Survival Analysis of Cardiology Patients**       
*Spring 2016*      
- Implemented a random survival forest on artificially balanced data and improved the sensitivity of the model by 35%
and extracted the 20 most important blood based features that help predict mortality      
- Cox proportional hazards model on balanced data predicted the time to event 58% better than the extant models

---

### Skills      
**Languages**: R, Python, SQL, Javascript   
**Frameworks**: Shiny, Flask, nodejs, Ruby on Rails   
**Expertise**: Machine Learning, Optimization, Data Wrangling, Data Analysis, Technical Communication

-->